### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

### ISSUE THREAD

**Issue by xdajay** [QingWei-Li/docsify#308]
SSR is not able to render pages.

code`
var Renderer = require('docsify-server-renderer')
var serveStatic = require('serve-static')
var http = require('http')
var fs = require('fs')
var renderer = new Renderer({
  template: `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>docsify Server</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">
</head>
<body>
  
  
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
</body>
</html>`,
  config: {
    name: 'docsify',
    repo: 'qingwei-li/docsify/master/docs/',
    basePath: 'https://raw.githubusercontent.com/QingWei-Li/docsify/master/docs/',
    loadNavbar: true,
    loadSidebar: true,
    subMaxLevel: 3,
    auto2top: true,
    alias: {
      '/de-de/changelog': '/changelog',
      '/zh-cn/changelog': '/changelog',
      '/changelog':
        'https://raw.githubusercontent.com/QingWei-Li/docsify/master/CHANGELOG'
    }
  },
  path: './'
})

http.createServer(function (req, res) {
    serveStatic('.')(req, res, function () {
      // Server side
        renderer.renderToString(req.url)
        .then(html => res.end(html))

      res.writeHead(404, { 'Content-Type': 'text/html' })
       // Clinet side       
      //res.end(fs.readFileSync('client.html'))
    })
  })
  .listen(4000)

console.log("4000")
  `

Error 

`0|app      | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|app      | TypeError: Cannot read property 'length' of undefined
0|app      | Please report this to https://github.com/chjj/marked.
0|app      |     at Compiler.matchNotCompileLink (/Users/ajaythakur/node_modules/docsify-server-renderer/build.js:470:29)
0|app      |     at Renderer.origin.link.renderer.link (/Users/ajaythakur/node_modules/docsify-server-renderer/build.js:538:14)
0|app      |     at InlineLexer.outputLink (/Users/ajaythakur/node_modules/marked/lib/marked.js:707:21)
0|app      |     at InlineLexer.output (/Users/ajaythakur/node_modules/marked/lib/marked.js:622:19)
0|app      |     at Parser.tok (/Users/ajaythakur/node_modules/marked/lib/marked.js:1075:50)
0|app      |     at Parser.parse (/Users/ajaythakur/node_modules/marked/lib/marked.js:935:17)
0|app      |     at Function.Parser.parse (/Users/ajaythakur/node_modules/marked/lib/marked.js:922:17)
0|app      |     at marked (/Users/ajaythakur/node_modules/marked/lib/marked.js:1219:19)
0|app      |     at /Users/ajaythakur/node_modules/docsify-server-renderer/build.js:459:12
0|app      |     at Compiler.cachedFn [as compile] (/Users/ajaythakur/node_modules/docsify-server-renderer/build.js:134:33)
0|app      | (node:7830) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'length' of undefined
0|app      | Please report this to https://github.com/chjj/marked.
0|app      | (node:7830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|app      | (node:7830) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'length' of undefined
0|app      | Please report this to https://github.com/chjj/marked.
`

**Comment by xdajay** [comment]
This issue arrives, if you have use incorrect links for md's
