### ISSUE TITLE
Error in docsify serve docs

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [QingWei-Li/docsify#454]
> $ docsify serve docs
`
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. ***

Serving C:\Users\pc 01\Documents\vuenut-page\docs now.
Listening at http://localhost:3000

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::35729
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Server.listen (C:\Users\pc 01\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\livereload\lib\livereload.js:69:28)
    at Object.exports.createServer (C:\Users\pc 01\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\livereload\lib\livereload.js:229:14)
    at Object.module.exports [as serve] (C:\Users\pc 01\AppData\Roaming\npm\node_modules\docsify-cli\lib\commands\serve.js:30:12)
    at Object.handler (C:\Users\pc 01\AppData\Roaming\npm\node_modules\docsify-cli\bin\docsify:77:28)
    at Object.self.runCommand (C:\Users\pc 01\AppData\Roaming\npm\node_modules\docsify-cli\node_modules\yargs\lib\command.js:231:22)
`

**Comment by QingWei-Li** [comment]
The 3000 port is be used in your system. So you should change a port.

**Comment by omaromp2** [comment]
Im having this error with any port.
![image](https://user-images.githubusercontent.com/3978597/46743505-36f4fd80-cc77-11e8-875a-ee8f72991658.png)

**Comment by omaromp2** [comment]
Nevermid got it to work! Yup it came down to the ports!
